import Head from 'next/head'
import { Nightlight, LinkedIn, Email, GitHub } from '@mui/icons-material/';
import Image from 'next/image'
import chess from '../public/chess.png'
import bishop from '../public/bishop.png'
import vn from '../public/KienGiang.jpg'
import ou from '../public/ou.png'

import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Thomas Nguyen Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <nav className='py-10 mb-12 flex justify-between sticky top-0 bg-white dark:bg-gray-900'>
          <h1 className='text-2xl font-mono dark:text-white'><a href='#top'>Thomas Nguyen</a></h1>
          <h1 className='text-2xl font-mono dark:text-white'><a href='#projects'>Projects</a></h1>
          <ul className='flex items-center'>
            <li>
              <Nightlight onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-white' />
            </li>
            <li>
              <a className="bg-gradient-to-r from-cyan-500 to-teal-500 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8" href='#'>Resume</a>
            </li>
          </ul>
        </nav>

        <section className='min-h-screen'>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Thomas Nguyen</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Chess Player and Vietnamese Learner</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white'>A 3rd year computer science student with a drive
              for playing Vietnamese Taboo and enjoying the beauty
              of chess. Join me on my journey of learning my heritage
              language and pursuing my dream of becoming a chess master!
            </p>
          </div>

          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white'>
            <LinkedIn />
            <Email />
            <GitHub />
          </div>

          <div className='bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 mx-auto dark:rounded-none'>
            <Image src={chess} alt="Chess pieces with Vietnamese color" />

          </div>
        </section>

        <section>
          <div className='align-center'>
            <h3 className='text-3xl py-1 dark:text-white mx-auto'>More about my hobbies</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              I started learning <span className='text-teal-500'>Vietnamese</span> around the time of the COVID-19 pandemic.
              Ever since then, I decided to practice speaking and learning Vietnamese every day.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              I love to play all kinds of board and strategy games but <span className='text-teal-500'>Chess</span> is by far my most favorite.
              I get to make so many cool friends while talking over a few chess games. I like chess because it forces me to really think and have a plan
              under time pressure.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              In the 9th grade, my guitar teacher introduced me to the world of programming when he showed me a program he made in Lisp that simulated
              the card game {"Set"} that we always played in our free time. I decided to study <span className='text-teal-500'>Computer Science </span>
              in university because I believe programming is a superpower that I can use to make my dreams and imaginations come true.
            </p>
          </div>

          <div className='lg:flex gap-10 justify-center'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white' >
              <Image className='mx-auto' src={vn} alt='Kien Giang logo' width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Learning Vietnamese</h3>
              <p className='py-2'>Có công mài sắt, có ngày nên kim.</p>
              <h4 className='py-4 text-teal-600'>Vietnamese Resources</h4>
              <p className='text-gray-800 py-1'><a href='https://www.free4talk.com/'>Free4Talk</a></p>
              <p className='text-gray-800 py-1'><a href='https://vnexpress.net/'>VNExpress</a></p>
              <p className='text-gray-800 py-1'><a href='https://vtudien.com/'>Vtudien</a></p>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white' >
              <Image className='mx-auto' src={bishop} alt='A bishop' width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Chess Journey</h3>
              <p className='py-2'>Starting the 11th grade, I started competing in chess tournaments.</p>
              <h4 className='py-4 text-teal-600'>Personal Statistics</h4>
              <p className='text-gray-800 py-1'>USCF Rating: 1738</p>
              <p className='text-gray-800 py-1'>State Ranking: 41/493</p>
              <p className='text-gray-800 py-1'>Current Norms: None</p>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image className='mx-auto' src={ou} alt='OU logo' height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Computer Science B.S.</h3>
              <p className='py-2'>University of Oklahoma May 2024</p>
              <h4 className='py-4 text-teal-600 '>Campus Involvement</h4>
              <p className='text-gray-800 py-1'>Engineering Tutor</p>
              <p  id='projects' className='text-gray-800 py-1'>Chess Club President</p>
              <p    className='text-gray-800 py-1'>Diversity and Inclusion Program</p>
            </div>

          </div>

        </section>

        <section>
          <div className='align-center'>
            <h3 className='text-3xl py-1 dark:text-white mx-auto'>Personal Projects</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white' >
              In my free time, I like to program useful tools that help me and my friends have a fun experience learning
              and playing on the internet. My creations range from chess visualization practice, language learning tools, and 
              external game utilities like a chat room service and roles randomizer. 
            </p>
          </div>

          <div className='lg:flex gap-10 justify-center'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
          <a href="https://spicy-chess-colors.netlify.app/" >
            <h2>Chess Colors &rarr;</h2>
            <p>Train your board vision with by identifying the color of a random chess square.</p>
          </a>
          </div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
          <a href="https://game-of-chance.vercel.app/" >
            <h2>A Game of Chance &rarr;</h2>
            <p>Maximize points by guessing if a number Y is higher or lower than a number X.</p>
          </a>
          </div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
          <a href="https://diffchecker-alpha.vercel.app/">
            <h2>Difference Checker &rarr;</h2>
            <p>Given two input text boxes, return their similiarity as a percentage.</p>
          </a>
          </div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
          <a href="https://masoi.vercel.app/" >
            <h2>Ma Sói Helper &rarr;</h2>
            <p>Randomize player names and roles.</p>
          </a>
          </div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
          <a href="https://spicy-chat.herokuapp.com/">
            <h2>Chat Rooms &rarr;</h2>
            <p>A free group web chat service.</p>
          </a>
          </div>
        </div>

        </section>

        
      </main>
    </div>
  )
}
